### ISSUE TITLE
Unable to Fetch responses from the student on submitting the test.

### ISSUE THREAD

**Issue by saurabhranjan1806** [sehgalayush1/labquiz#4]
On trying to get the values of Checkboxes that are responded in the views, using getlist method, it returns empty list. The QuerySet contains all the responses but can't fetch from it. 
![image](https://user-images.githubusercontent.com/15872681/28201258-e205184e-688d-11e7-9b8d-bf10dcf0fd6a.png)

**Comment by sehgalayush1** [comment]
what is result.py doing?

**Comment by saurabhranjan1806** [comment]
It is just a python file containing a function which is called from the view function 'allQuestions'. I created this because code was getting messy on adding all the code inside one function. I have tried all this from the views 'allQuestions'  function too, still not able to fetch the answers.

**Comment by sehgalayush1** [comment]
Don't transfer request from views.py to another file. If you want, create a new function to handle the request.

**Comment by saurabhranjan1806** [comment]
ok, i will remove it.

**Comment by saurabhranjan1806** [comment]
Removed result.py, still the same problem.

**Comment by sehgalayush1** [comment]
Ok, I will create a new branch and resolve your bug.

**Comment by sehgalayush1** [comment]
I have push a new branch with your bug resolved.
