### ISSUE TITLE
Use radio buttons for answers since these are single choice questions

### ISSUE THREAD

**Issue by sehgalayush1** [sehgalayush1/labquiz#6]
Use radio buttons for now and later add a feature which allow the teacher to specify the type for each question (whether he/she wants single or multiple correct answers for the question). Use checkboxes for multiple correct answers.

**Comment by saurabhranjan1806** [comment]
Presently, all are multiple choice questions, Teachers can create an exam and can add only the multiple choice questions, therefore i have used checkboxes. I have to first change that in teachers, or add their a choice asking single correct or multiple correct and then add radio buttons for single correct.

**Comment by sehgalayush1** [comment]
Just add radio button in both the places... where teacher selects the correct answer and where student selects the correct answer. Make a proper fix later.

**Comment by saurabhranjan1806** [comment]
Done. Will add an option for teachers to specify multiple choice or single choice question later
